[package]
name = "lz-fear"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]
edition = "2018"

description = "A fast pure-rust no-unsafe implementation of LZ4 compression and decompression"
keywords = ["compression", "lz4", "compress", "decompression", "decompress"]
categories = [ "algorithms", "compression", "encoding" ]
#license = "MIT" license undecided
readme = "README.md"

repository = "https://github.com/main--/rust-lz-fear"

[dependencies]
byteorder = "1.3.1"
twox-hash = "1.5.0"
thiserror = "1.0"
fehler = "1.0"
cfg-if = "0.1.10"

[dev-dependencies]
criterion = "0.3"
rand = "0.7.3"

[[bench]]
name = "my_benchmark"
harness = false

[profile.release]
debug = true
lto = "thin"
